### ISSUE TITLE
[RESOLVED] Implicit Conversion Warnings

### ISSUE THREAD

**Issue by Steviey** [darwinex/DarwinexLabs#10]
DWX_ZeroMQ_Server_v2.0.1_RC8

I get a bunch of warnings...actually can't been overseen...

implicit conversion from 'number' to 'string'	(multiple lines)
declaration of 'data' hides global declaration in file [...] Z85.mqh (multiple lines)
expression not boolean	GlobalVariable.mqh (multiple lines)

By the way, is this server version for Python only? 
I can't find any information, on how to handle the versions in regard to R.
And is it OK to use the old version because of its simple, easy to extend structur?

Thank you.

**Comment by TimKabue** [comment]
ZeroMQ works with both Python and R. If you scroll through this webpage: https://blog.darwinex.com/zeromq-interface-python-r-metatrader4/ at the very end is the sub topic 'Sample Code' where you can find a link to ZeroMQ implemented in R. This is the actual link: https://github.com/darwinex/DarwinexLabs/blob/master/tools/R/ZeroMQ_MT4_R_Template.R

**Comment by integracore2** [comment]
Hi @Steviey ,

Thank you for raising this - could you please paste a text log of the warnings generated?

**Comment by integracore2** [comment]
**[UPDATE]** Warnings resolved in an updated **DWX_ZeroMQ_Server_v2.0.1_RC8**.

Changes will be committed shortly.
