### ISSUE TITLE
[DEPRECATED] ZeroMQ_MT4_R_Template.R freezes RStudio (fixed but lost functional version)

### ISSUE THREAD

**Issue by Steviey** [darwinex/DarwinexLabs#12]
ZeroMQ_MT4_R_Template.R freezes RStudio because of an issue related to stdin.
I was able to fix it like so: 

```
while(TRUE){
    content <- readLines(stdin(), n=1)
    if(content=='ex'){
        print(paste('End Command:',content))
        break
    }
```
Actually I had a fully functional version. But since two days, I'm not able to recreate it. It's totally strange. 
In my opinion exceptions are crucial in the 'socket-land', keyword 'deadlocks'. So server and clients have to use an extensive amount of checks and exceptions. Connections, bindings and contexts have to be closed, terminated etc. decently. Otherwise any debugging is nothing less then hell. 

Latest R/Win7/MT4

**Comment by integracore2** [comment]
Hi @Steviey,

Great, thanks for pointing this out.

Please note that this R script is deprecated - we are not maintaining it our end.

You are of course welcome to continue your own development, and should you have something tangible that you'd like to share, please do let us know and we'll reference it here on GitHub.
