### ISSUE TITLE
ZeroMQ-Server & MT4 Strategy Tester

### ISSUE THREAD

**Issue by Steviey** [darwinex/DarwinexLabs#14]
The event listener 'OnTimer()' is not implemented in strategy tester.
Therefore triggering instead via 'OnTick()' does the trick within strategy tester.
I've got this working with the older version of the server script and a R-Client. 
The newer one freezes the strategy tester, if triggered via 'OnTick()'. Any ideas here?

**Comment by integracore2** [comment]
Hi @Steviey ,

Interesting - thanks for flagging this.

We'll investigate internally and come back with an update.
