### ISSUE TITLE
[BENCHED] [paduel/darwinex_ticks] ModuleNotFoundError Issue

### ISSUE THREAD

**Issue by tomasvanek** [darwinex/DarwinexLabs#15]
I have tested your script in command line but I received this error. I have installed all modules python 2.7, pandas, and Darwin tick. Please, could you help me?

`python -m darwinex_ticks EURGBP EURGBP USDJPY -u username -w passsword -n tickdata.darwinex.com -s "2018-10-08 10" -e "2018-10-08 12" -g`

```

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/darwinex_ticks/__main__.py", line 7, in <module>
    except ModuleNotFoundError:
```

**Comment by integracore2** [comment]
Hi @tomasvanek ,

Thank you for your query.

It appears from your traceback that you're referring to **darwinex_ticks**, which is a repo authored and maintained by GitHub user **@paduel**, not Darwinex.

**I recommend creating an issue for this here:**
https://github.com/paduel/darwinex_ticks/issues

Our version of the tick data scripts is in Python 3, accessible via:
https://github.com/darwinex/DarwinexLabs/tree/master/tools/Python/Tick-Data

**Comment by paduel** [comment]
Hi @tomasvanek ,

thank you for report, but like @integracore2 said, new time better creating an issue at my github
[https://github.com/paduel/darwinex_ticks/issues](https://github.com/paduel/darwinex_ticks/issues).

When I tested the module using Python 2.7 worked nice, but I have modified the code to avoid this error. Please update the module to the new version 0.1.5
