### ISSUE TITLE
Error 129 : Invalid Price Error

### ISSUE THREAD

**Issue by diliproshitha** [darwinex/DarwinexLabs#16]
I am getting an Error with code 129 (Invalid Price). My python code is : 
```
from DWX_ZeroMQ_Connector_v2_0_1_RC8 import DWX_ZeroMQ_Connector

_zmq = DWX_ZeroMQ_Connector()
_zmq._DWX_MTX_NEW_TRADE_()
```

I tried several days by changing EA code. But I could not resolve this.

**Comment by integracore2** [comment]
Hi @diliproshitha ,

Thank you for your query.

Executing _zmq._DWX_MTX_NEW_TRADE_() will send the default order dict contents to MetaTrader -> which is an instruction to MetaTrader to open an order on the EUR/USD at market (whatever price is available at the time).

Error 129 implies that the price at which MetaTrader is executing the order "no longer exists", which is strange indeed.

Could you confirm if you are using the latest, most up to date Python script here?

Are you using Darwinex as the broker? If not, look into the instrument specification of EUR/USD there as a place to start.

Here to help you get up and running, no worries!

**Comment by diliproshitha** [comment]
Hi @integracore2,
Thank you for the response. I could resolve my issue by updating mt4. Yes I am using Darwinex as the broker. :)

**Comment by integracore2** [comment]
That's fantastic @diliproshitha - great to hear you were able to resolve the issue! 🙂
