### ISSUE TITLE
Can't compile DWX_ZeroMQ_Server_v2.0.1_RC8.mq4

### ISSUE THREAD

**Issue by gobllyn** [darwinex/DarwinexLabs#17]
When trying to compile the expert on MT4 MetaEditor it gives me some errors.
-Single quote needed ( Lines : 147, 390,506,518...)
-Unknown symbol ( Lines : 147, 390,506,518)
-Invalid prepocessor command ( Lines : 2121...)

Any idea what can be the issue?
Thanks

**Comment by integracore2** [comment]
Hi @gobllyn ,

Here to help, no worries.

Could you confirm if you've followed the installation instructions and are using scripts available via the new repository?

Link:
https://github.com/darwinex/dwx-zeromq-connector

Regardless, all previous code should also compile successfully, so there is likely a missing library or other configuration issue causing this.

The installation instructions provided in the README.md should enable a fairly straightforward installation for everyone.

Hope this helps!
