### ISSUE TITLE
Cannot call 'libzmq.dll::zmq_ctx_new', DLL is not allowed

### ISSUE THREAD

**Issue by jackshankenburg** [darwinex/DarwinexLabs#18]
Just a heads up, I did a fresh install of MT4 and DLL imports were preset to off.

To fix, Tools > Options > Expert Advisors > Allow DDL Imports.

I also checked Allow Automated Trading.

Thank you for all of the open source code.

**Comment by integracore2** [comment]
Great to hear you were able to resolve the DLL issue @jackshankenburg .

You're very welcome!

**Comment by mehedi02** [comment]
but it still shows error after doing Tools > Options > Expert Advisors > Allow DDL Imports

**Comment by jackshankenburg** [comment]
I experienced a second issue with ibzmq.dll. I did a fresh install on a Windows 10, 64 bit machine and couldn't get libzmq.dll to load.

Found the answer here https://github.com/dingmaotu/mql-zmq/issues/17

libzmq.dll requires Microsoft Visual C++ 2015 Redistributable (x86) to compile.

**Comment by integracore2** [comment]
Thank you for sharing your debug experience here @jackshankenburg !

We’ll update our documentation to reflect this dependency.

**Comment by satz275** [comment]
@jackshankenburg  - I am still having issues, same error.
OS specification Windows 10 Pro

**Comment by satz275** [comment]
Error Msg-
2020.03.04 12:01:33.054	Cannot call 'libzmq.dll::zmq_ctx_new', DLL is not allowed
2020.03.04 12:01:33.054	DWX_ZeroMQ_Server_v2.0.1_RC8 USDJPY,H1: unresolved import function call
2020.03.04 12:01:33.059	DWX_ZeroMQ_Server_v2.0.1_RC8 USDJPY,H1: global initialization failed.

I tried all the optioned and nothing is workings.

**Comment by satz275** [comment]
2020.03.04 12:23:12.929	Cannot load 'C:\Users\test\AppData\Roaming\MetaQuotes\Terminal\3B534B10135CFEDF8CD1AAB8BD994B13\MQL4\Libraries\libzmq.dll' [126]- Error Msq

**Comment by paul-jackson-dev** [comment]
@satz275 

libzmq.dll requires Microsoft Visual C++ 2015 Redistributable (x86) to compile. 

Good luck.

**Comment by satz275** [comment]
@jackshankenburg  - It is working now

Thanks for your support. much appreciated !!!
