### ISSUE TITLE
why using zeromq?

### ISSUE THREAD

**Issue by amin1softco** [darwinex/DarwinexLabs#2]
hi 
i want implement machine learning/deep learning method in meta trader and find multiple approach 
1- ENCOG  library  connect to mt with simple dll
2- ALGLIB  library  connect to mt with simple dll
3- mt4Rb7.dll can connect directly to R
4- matlab using read/write on single file
5- zeromq using socket to connect python / R

what is your opinion and what is best approach? and why ?

**Comment by JonB451** [comment]
Hi, i would be interested in hearing a response to your questions to. Thanks for asking them. Have you thought of posting them at either of these? If you do post them there could you also please let us know here so that we can follow them there?

[https://github.com/dingmaotu/mql-zmq/issues](https://github.com/dingmaotu/mql-zmq/issues)
[http://zeromq.org/topics:_start](http://zeromq.org/topics:_start)

**Comment by amin1softco** [comment]
I just asked my question here. 
but i think read/ write on file stable than other approach and can use in any language. only get historical data from mt4/5 and write on history file after processing then write result on resultfile and mt4 can read those file in each tick and do your work simple and can use any language.

**Comment by JonB451** [comment]
Thanks for updating @amin1softco .

It's a shame that no one has answered. Maybe i will post the questions at those other places.

Working on files seems the most straightforward to me too and is what i've been doing in the past.  But it has limitations that i hoped some of the things in your list could overcome.

**Comment by integracore2** [comment]
> hi
> i want implement machine learning/deep learning method in meta trader and find multiple approach
> 1- ENCOG library connect to mt with simple dll
> 2- ALGLIB library connect to mt with simple dll
> 3- mt4Rb7.dll can connect directly to R
> 4- matlab using read/write on single file
> 5- zeromq using socket to connect python / R
> 
> what is your opinion and what is best approach? and why ?

@amin1softco @JonB451 - Firstly, sincere apologies for your queries not being addressed sooner - this will change effective immediately. Going forward this repository will be actively monitored for queries/issues as they surface.

As for your question:

For your list of use-cases, by far the simplest approach would involve either flat-file based transactions or ZeroMQ. We've argued the reason for ZeroMQ-enabled connectivity to MetaTrader in the following articles:

1) [ZeroMQ – How To Interface Python/R with MetaTrader 4](https://blog.darwinex.com/zeromq-interface-python-r-metatrader4/)

2) [ZeroMQ – Trade Execution in MetaTrader (ZMQ-II)](https://blog.darwinex.com/zeromq-trade-execution-metatrader-zmq2/)

3) [ZeroMQ – Transaction Reporting via MetaTrader (ZMQ-III)](https://blog.darwinex.com/zeromq-transaction-reporting-metatrader-zmq3/)

You may also wish to watch the following recording of a webinar we did on the same:
[Webinar Replay - ZeroMQ & MetaTrader](https://www.youtube.com/watch?v=GGOajzvl860&t=1s)

I hope this proves useful - please do keep your questions coming!

**Comment by amin1softco** [comment]
hi 
i think python don't need any third party library for communication with mt4 
python + bottle can become simple web-service and mt4 can request json with WebRequest and simply every think work like charm. but for R maybe 0mq is good solution.

**Comment by integracore2** [comment]
> hi
> i think python don't need any third party library for communication with mt4
> python + bottle can become simple web-service and mt4 can request json with WebRequest and simply every think work like charm. but for R maybe 0mq is good solution.

Thank you for your inputs @amin1softco ! We'll certainly keep this in mind as we expand on this project 👍

**Comment by JonB451** [comment]
Thanks for another update @amin1softco 

Is this the conclusion of your search for a way to integrate MT4/MQL with Python: MT4 requesting JSON from Python+Bottle with WebRequest()? Does that work at an OnTick() speed?

**Comment by amin1softco** [comment]
> 
> 
> Thanks for another update @amin1softco
> 
> Is this the conclusion of your search for a way to integrate MT4/MQL with Python: MT4 requesting JSON from Python+Bottle with WebRequest()? Does that work at an OnTick() speed?

yes work great ever in strategy tester .
