### ISSUE TITLE
Connect two MT4 terminals

### ISSUE THREAD

**Issue by ildeb** [darwinex/DarwinexLabs#21]
Would it be possible to send commands from python to two MT4 terminals connected simultaneously?

**Comment by integracore2** [comment]
Hi @ildeb ,

Yes this is indeed possible.

You would need to create two instances of the DWX_ZeroMQ_Connector object in your Python implementation, with unique port combinations (these being what you've configured your EAs in MetaTrader to have).

Each MetaTrader terminal must have different PUSH/PULL ports configured.

For market data, if one of the terminals is publishing data then that should be enough for subscribing applications to receive data.

You could technically dedicate one terminal specifically as the "price publisher".
