### ISSUE TITLE
Metatrader can't open DWX_ZeroMQ_Server_vX.Y.Z_RCx.mq4 

### ISSUE THREAD

**Issue by avarf** [darwinex/DarwinexLabs#28]
I followed the isntructions for installing the https://github.com/darwinex/DarwinexLabs/tree/master/tools/dwx_zeromq_connector but when I drag the DWX_ZeroMQ_Server_vX.Y.Z_RCx.mq4 to the chart I get:
```
cannot open file 'C:\Users\fo\AppData\Roaming\MetaQuotes\Terminal\E6734F6041F45FBC490D7BD7FB1CB8E3\MQL4\Experts\DWX_ZeroMQ_Server_v2.0.1_RC8.ex4' [2]
```
How I can solve this?

**Comment by avarf** [comment]
The problem was that I didn't know that I had to compile the DWX_ZeroMQ_Server_vX.Y.Z_RCx.mq4 before adding it to the chart and there was nothing about that in the documentation.

**Comment by hisham-ash** [comment]
Same here now, I have only 1 Error after compilation. Can you please help me fix it?

 m_hm = new HM;                  ## in Global Variable.mqh ##  I'm getting this error '=' - type mismatch      GlobalVariable.mqh
