### ISSUE TITLE
Sending requests longer than RATES|SYMBOL crashes MetaTrader 4

### ISSUE THREAD

**Issue by blairits** [darwinex/DarwinexLabs#3]
Hello,

I was trying to set this up. But when sending rquests longer then the RATES|GBPUSD command causes an error in ZeroMQ_MT4_EA_Template.mq4 and MetaTrader 4 crashes.

**Comment by rotem443** [comment]
Same for me, Help please!

**Comment by integracore2** [comment]
> Hello,
> 
> I was trying to set this up. But when sending rquests longer then the RATES|GBPUSD command causes an error in ZeroMQ_MT4_EA_Template.mq4 and MetaTrader 4 crashes.

Hi @blairits,

We are in the process of releasing updated versions of all code concerning ZeroMQ to MetaTrader connectivity. New code releases will provide significant improvements to previous releases, and also support Python 3.6+!

Stay tuned for updates, and apologies for the delay in responding to your queries! 👍
