### ISSUE TITLE
TypeError: unicode not allowed, use send_string

### ISSUE THREAD

**Issue by masfen** [darwinex/DarwinexLabs#5]
good day

first off thank you for your contribution to this matter, unfortunately I am getting an error  

  File "zmq/backend/cython/socket.pyx", line 676, in zmq.backend.cython.socket.Socket.send

TypeError: unicode not allowed, use send_string

could you please help me

**Comment by blairits** [comment]
Hello, this is not a problem with this code it is a zmq-lib(i think) problem post on there page.

**Comment by integracore2** [comment]
> good day
> 
> first off thank you for your contribution to this matter, unfortunately I am getting an error
> 
> File "zmq/backend/cython/socket.pyx", line 676, in zmq.backend.cython.socket.Socket.send
> 
> TypeError: unicode not allowed, use send_string
> 
> could you please help me

Hi @masfen @blairits,

Sincere apologies for the delayed response to your queries - going forward, this repository will be actively monitored for issues/queries as they surface.

We are in the process of releasing updated version of all code concerning ZeroMQ to MetaTrader connectivity. New code releases will provide  significant improvements to previous releases, and also support Python 3.6+!

Stay tuned for updates 👍
